version: "3.8"

services:
    web:
        build: .
        image: chat_app:latest
        container_name: chat_app
        ports:
            - "8000:5000"
        env_file: .env
        depends_on: 
            - dynamodb-local
    dynamodb-local:
        command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
        image: "amazon/dynamodb-local:latest"
        container_name: dynamodb-local
        ports:
            - "8000:8000"
        volumes:
            - "./docker/dynamodb:/home/dynamodblocal/data"
        working_dir: /home/dynamodblocal